// ── Colors ─────────────────────────────────────────────────────────────────

export const DAY_COLORS = ["#00C6FF", "#FF6B6B", "#A8FF78", "#F7971E"];

export const HC = "#FF3D71";

export const MUSCLE_COLORS: Record<string, string> = {
  Lats: "#00C6FF",
  Biceps: "#A78BFA",
  Shoulder: "#FF6B6B",
  Shoulders: "#FF6B6B",
  Chest: "#FB923C",
  Triceps: "#FCD34D",
  Quads: "#A8FF78",
  Hamstrings: "#4ADE80",
  Glutes: "#F472B6",
  Calves: "#67E8F9",
  Back: "#FB923C",
  "Rear Delt": "#E879F9",
  Traps: "#FCD34D",
  Core: "#94A3B8",
};

// ── Day metadata ────────────────────────────────────────────────────────────

export const DAY_META = [
  { label: "DAY 1", name: "PULL — Wide Back", focus: "Lats · Biceps" },
  {
    label: "DAY 2",
    name: "PUSH — Shoulders & Chest",
    focus: "Deltoids · Chest · Triceps",
  },
  {
    label: "DAY 3",
    name: "LEGS — Full Legs",
    focus: "Quads · Hamstrings · Glutes",
  },
  {
    label: "DAY 4",
    name: "UPPER — Thick Back & Rear Delts",
    focus: "Traps · Rear Delt · Strength",
  },
];

// ── Exercise pools ──────────────────────────────────────────────────────────

export const DAY_POOLS = [
  [
    {
      name: "Wide Pronated Grip Pull-ups",
      muscle: "Lats",
      sets: "4",
      reps: "6–10",
      notes: "Priority #1 for the V-taper. Grip wider than shoulder width.",
      rec: true,
    },
    {
      name: "Pronated Grip Lat Pulldown",
      muscle: "Lats",
      sets: "4",
      reps: "8–12",
      notes: "Alternative to pull-ups. Same movement pattern.",
    },
    {
      name: "Supinated Grip Lat Pulldown",
      muscle: "Lats",
      sets: "3",
      reps: "10–12",
      notes: "Greater biceps and lower lat recruitment.",
    },
    {
      name: "Barbell Row",
      muscle: "Lats",
      sets: "4",
      reps: "5–8",
      notes: "Flat back, elbows tight. Great mass builder.",
      rec: true,
    },
    {
      name: "Pendlay Row",
      muscle: "Lats",
      sets: "4",
      reps: "5–8",
      notes: "From the floor. More explosive, allows heavier load.",
    },
    {
      name: "Single-Arm Dumbbell Row",
      muscle: "Lats",
      sets: "3",
      reps: "10–12",
      notes: "Full range. Slightly rotate the torso on the way up.",
      rec: true,
    },
    {
      name: "Dumbbell Pullover",
      muscle: "Lats",
      sets: "3",
      reps: "10–12",
      notes: "Great lat stretch. Slow on the way down.",
      rec: true,
    },
    {
      name: "Cable Row (neutral grip)",
      muscle: "Lats",
      sets: "3",
      reps: "10–12",
      notes: "Squeeze scapulas at the end of the range.",
      rec: true,
    },
    {
      name: "Cable Row (pronated grip)",
      muscle: "Lats",
      sets: "3",
      reps: "12–15",
      notes: "Greater mid-trap and rhomboid activation.",
    },
    {
      name: "Straight-Arm Cable Pulldown",
      muscle: "Lats",
      sets: "3",
      reps: "12–15",
      notes: "Pure lat isolation. Arms almost straight.",
    },
    {
      name: "Machine Row (Hammer Strength)",
      muscle: "Lats",
      sets: "3",
      reps: "10–12",
      notes: "Unilateral overload. Useful for correcting imbalances.",
    },
    {
      name: "EZ Bar Curl",
      muscle: "Biceps",
      sets: "3",
      reps: "10–12",
      notes: "Classic. No swinging, controlled on the way down.",
      rec: true,
    },
    {
      name: "Straight Bar Curl",
      muscle: "Biceps",
      sets: "3",
      reps: "10–12",
      notes: "More supination = bigger biceps peak.",
    },
    {
      name: "Hammer Curl",
      muscle: "Biceps",
      sets: "3",
      reps: "12–15",
      notes: "Works brachialis and forearm in addition to biceps.",
    },
    {
      name: "Incline Dumbbell Curl",
      muscle: "Biceps",
      sets: "3",
      reps: "10–12",
      notes: "Maximum stretch. Very effective for the peak.",
    },
    {
      name: "Cable Curl",
      muscle: "Biceps",
      sets: "3",
      reps: "12–15",
      notes: "Constant tension. Better pump than dumbbells.",
    },
    {
      name: "Concentration Curl",
      muscle: "Biceps",
      sets: "2",
      reps: "12–15",
      notes: "Maximum isolation. 1 sec pause at the top.",
    },
    {
      name: "Cable Face Pulls",
      muscle: "Rear Delt",
      sets: "3",
      reps: "15–20",
      notes: "Fundamental for shoulder health and rear V-taper.",
    },
  ],
  [
    {
      name: "Standing Barbell Overhead Press",
      muscle: "Shoulder",
      sets: "4",
      reps: "5–8",
      notes: "Key for width. Progressive overload each week.",
      rec: true,
    },
    {
      name: "Seated Dumbbell Overhead Press",
      muscle: "Shoulder",
      sets: "4",
      reps: "8–10",
      notes: "Greater range of motion than barbell.",
    },
    {
      name: "Arnold Press",
      muscle: "Shoulder",
      sets: "3",
      reps: "10–12",
      notes: "Rotate dumbbells on the way up. Activates all 3 deltoid heads.",
    },
    {
      name: "Dumbbell Lateral Raises",
      muscle: "Shoulder",
      sets: "4",
      reps: "12–15",
      notes: "The most important for the V-taper. No cheating.",
      rec: true,
    },
    {
      name: "Cable Lateral Raises",
      muscle: "Shoulder",
      sets: "3",
      reps: "12–15",
      notes: "Constant tension. Superior to dumbbells for hypertrophy.",
      rec: true,
    },
    {
      name: "Cross-Cable Lateral Raises",
      muscle: "Shoulder",
      sets: "3",
      reps: "12–15",
      notes: "Tension throughout the arc. Unilateral.",
    },
    {
      name: "Dumbbell Front Raises",
      muscle: "Shoulder",
      sets: "3",
      reps: "12–15",
      notes: "Anterior deltoid. Complement to the press.",
    },
    {
      name: "Incline Barbell Press",
      muscle: "Chest",
      sets: "3",
      reps: "8–10",
      notes: "45°. Upper chest + anterior deltoid.",
      rec: true,
    },
    {
      name: "Incline Dumbbell Press",
      muscle: "Chest",
      sets: "3",
      reps: "8–12",
      notes: "Greater range of motion and better stretch.",
    },
    {
      name: "Flat Barbell Bench Press",
      muscle: "Chest",
      sets: "3",
      reps: "6–10",
      notes: "Mid chest. Strength classic.",
    },
    {
      name: "Flat Dumbbell Press",
      muscle: "Chest",
      sets: "3",
      reps: "10–12",
      notes: "Greater pec stretch than barbell.",
    },
    {
      name: "Cable Crossover (high)",
      muscle: "Chest",
      sets: "3",
      reps: "12–15",
      notes: "Lower chest. Strong contraction in the center.",
      rec: true,
    },
    {
      name: "Flat Dumbbell Flyes",
      muscle: "Chest",
      sets: "3",
      reps: "12–15",
      notes: "Deep stretch. Moderate weight.",
    },
    {
      name: "Parallel Bar Dips",
      muscle: "Triceps",
      sets: "3",
      reps: "8–12",
      notes: "Upright torso for more triceps. Add weight if you can.",
      rec: true,
    },
    {
      name: "Cable Triceps Pushdown (rope)",
      muscle: "Triceps",
      sets: "3",
      reps: "12–15",
      notes: "Elbow pinned to body. Spread hands at the bottom.",
    },
    {
      name: "Skull Crushers",
      muscle: "Triceps",
      sets: "3",
      reps: "10–12",
      notes: "Excellent for the long head of the triceps.",
    },
    {
      name: "Close-Grip Bench Press",
      muscle: "Triceps",
      sets: "3",
      reps: "8–10",
      notes: "Compound. Moves more weight than any isolation.",
    },
    {
      name: "Dumbbell Triceps Kickback",
      muscle: "Triceps",
      sets: "3",
      reps: "12–15",
      notes: "Isolation. Arm parallel to the floor at the start.",
    },
  ],
  [
    {
      name: "Barbell Back Squat",
      muscle: "Quads",
      sets: "4",
      reps: "5–8",
      notes: "The king of lower body. Parallel depth minimum.",
      rec: true,
    },
    {
      name: "Front Squat",
      muscle: "Quads",
      sets: "4",
      reps: "6–8",
      notes: "Greater quad activation. Requires mobility.",
    },
    {
      name: "Barbell Hack Squat",
      muscle: "Quads",
      sets: "3",
      reps: "8–12",
      notes: "Focuses quads with less lower back stress.",
    },
    {
      name: "Bulgarian Split Squat",
      muscle: "Quads",
      sets: "3",
      reps: "8–12",
      notes: "Unilateral. Detects and corrects imbalances.",
      rec: true,
    },
    {
      name: "Leg Press",
      muscle: "Quads",
      sets: "3",
      reps: "10–12",
      notes: "Feet high = glutes. Feet low = quads.",
      rec: true,
    },
    {
      name: "Quad Extension",
      muscle: "Quads",
      sets: "3",
      reps: "12–15",
      notes: "Isolation. Only if there's no knee pain.",
    },
    {
      name: "Dumbbell Step-Ups",
      muscle: "Quads",
      sets: "3",
      reps: "10–12",
      notes: "Functional and unilateral. High bench or box.",
    },
    {
      name: "Romanian Deadlift (RDL)",
      muscle: "Hamstrings",
      sets: "3",
      reps: "10–12",
      notes: "Hamstrings and glutes. Very controlled stretch.",
      rec: true,
    },
    {
      name: "Good Mornings",
      muscle: "Hamstrings",
      sets: "3",
      reps: "10–12",
      notes: "Bar on back. Hip hinge. Moderate weight.",
    },
    {
      name: "Lying Leg Curl",
      muscle: "Hamstrings",
      sets: "3",
      reps: "12–15",
      notes: "Hamstring isolation. Full range of motion.",
      rec: true,
    },
    {
      name: "Seated Leg Curl",
      muscle: "Hamstrings",
      sets: "3",
      reps: "12–15",
      notes: "Greater tension in the stretch than lying.",
    },
    {
      name: "Barbell Hip Thrust",
      muscle: "Glutes",
      sets: "4",
      reps: "10–12",
      notes: "The best glute exercise. Progressive overload.",
      rec: true,
    },
    {
      name: "Dumbbell Lunges",
      muscle: "Glutes",
      sets: "3",
      reps: "10–12",
      notes: "Long step for more glute activation.",
    },
    {
      name: "Machine Hip Abduction",
      muscle: "Glutes",
      sets: "3",
      reps: "15–20",
      notes: "Glute medius. Important for hip aesthetics.",
    },
    {
      name: "Machine Hip Adduction",
      muscle: "Hamstrings",
      sets: "3",
      reps: "15–20",
      notes: "Inner thigh. Full range of motion.",
    },
    {
      name: "Standing Calf Raises",
      muscle: "Calves",
      sets: "4",
      reps: "15–20",
      notes: "Slow descent (3 sec) for more stimulation.",
      rec: true,
    },
    {
      name: "Seated Calf Raises",
      muscle: "Calves",
      sets: "3",
      reps: "15–20",
      notes: "Works the soleus more than standing.",
    },
    {
      name: "Single-Leg Press",
      muscle: "Quads",
      sets: "3",
      reps: "10–12",
      notes: "Unilateral. Detects differences between legs.",
    },
  ],
  [
    {
      name: "Conventional Deadlift",
      muscle: "Back",
      sets: "4",
      reps: "4–6",
      notes: "Max strength day. Maximum intensity.",
      rec: true,
    },
    {
      name: "Sumo Deadlift",
      muscle: "Back",
      sets: "4",
      reps: "4–6",
      notes: "Greater adductor and glute activation.",
    },
    {
      name: "Close Neutral Grip Lat Pulldown",
      muscle: "Lats",
      sets: "3",
      reps: "10–12",
      notes: "Inner lats and teres major.",
      rec: true,
    },
    {
      name: "Supinated Grip Lat Pulldown",
      muscle: "Lats",
      sets: "3",
      reps: "10–12",
      notes: "Greater biceps involvement. Good range.",
    },
    {
      name: "Single-Arm Dumbbell Row",
      muscle: "Lats",
      sets: "3",
      reps: "10–12",
      notes: "Full range. Rotate torso on the way up.",
      rec: true,
    },
    {
      name: "Chest-Supported Machine Row",
      muscle: "Lats",
      sets: "3",
      reps: "10–12",
      notes: "Eliminates lower back drive. Pure isolation.",
    },
    {
      name: "Wide Grip Cable Row",
      muscle: "Lats",
      sets: "3",
      reps: "10–12",
      notes: "Greater mid-trap activation.",
    },
    {
      name: "Cable Face Pulls",
      muscle: "Rear Delt",
      sets: "4",
      reps: "15–20",
      notes: "KEY for the V-taper. Rear shoulder + rotator cuff.",
      rec: true,
    },
    {
      name: "Dumbbell Rear Delt Fly",
      muscle: "Rear Delt",
      sets: "3",
      reps: "15–20",
      notes: "Leaning forward. Elbows slightly bent.",
      rec: true,
    },
    {
      name: "Reverse Pec Deck Rear Delt",
      muscle: "Rear Delt",
      sets: "3",
      reps: "15–20",
      notes: "Easier to isolate the rear delt. Good for pump.",
    },
    {
      name: "Incline Lateral Raises",
      muscle: "Shoulder",
      sets: "3",
      reps: "12–15",
      notes: "Pure lateral deltoid isolation.",
      rec: true,
    },
    {
      name: "Upright Row (cable)",
      muscle: "Traps",
      sets: "3",
      reps: "12–15",
      notes: "Works lateral deltoid and upper traps.",
    },
    {
      name: "Dumbbell Shrugs",
      muscle: "Traps",
      sets: "3",
      reps: "12–15",
      notes: "Upper traps. 1 sec pause at the top.",
    },
    {
      name: "Preacher Curl (Scott Bench)",
      muscle: "Biceps",
      sets: "3",
      reps: "10–12",
      notes: "Eliminates momentum. Maximum biceps peak.",
    },
    {
      name: "Single-Arm Hammer Curl",
      muscle: "Biceps",
      sets: "2",
      reps: "12–15",
      notes: "Brachialis and brachioradialis. Complete the arm.",
    },
    {
      name: "Spider Curl",
      muscle: "Biceps",
      sets: "2",
      reps: "12–15",
      notes: "Maximum tension at contraction. Inverted incline bench.",
    },
    {
      name: "Concentration Curl",
      muscle: "Biceps",
      sets: "2",
      reps: "12–15",
      notes: "Biceps peak. 1 sec pause at the top.",
      rec: true,
    },
    {
      name: "Cable Pull-Through",
      muscle: "Glutes",
      sets: "3",
      reps: "15–20",
      notes: "Hip hinge with constant tension.",
    },
  ],
];

// ── HIIT pool ───────────────────────────────────────────────────────────────

export const HIIT_POOL = [
  {
    name: "Burpees",
    emoji: "💥",
    desc: "Full body. Explosive on the jump, controlled on the way down.",
    rec: true,
  },
  {
    name: "Mountain Climbers",
    emoji: "🔥",
    desc: "Knees to chest at max pace. Core always tight.",
    rec: true,
  },
  {
    name: "Jump Squats",
    emoji: "⚡",
    desc: "Jump on the way up, land soft with knees bent.",
    rec: true,
  },
  {
    name: "High Knees",
    emoji: "🚀",
    desc: "Knees to hip height. Sprint in place, max pace.",
    rec: true,
  },
  {
    name: "Plank to Push-up",
    emoji: "💪",
    desc: "From high to low plank alternating arms. No hip swaying.",
    rec: true,
  },
  {
    name: "Jump Lunges",
    emoji: "🌋",
    desc: "Alternate legs in the air. The biggest burner in the circuit.",
    rec: true,
  },
  {
    name: "Box Jumps",
    emoji: "📦",
    desc: "Jump onto a box or elevated surface. Step down with control.",
  },
  {
    name: "Skaters (lateral jump)",
    emoji: "⛸️",
    desc: "Jump side to side landing on one foot. Lateral power.",
  },
  {
    name: "Tuck Jumps",
    emoji: "🦘",
    desc: "Jump and bring knees to chest. Maximum vertical power.",
  },
  {
    name: "Plank Jacks",
    emoji: "🎯",
    desc: "In plank position, open and close legs like a jumping jack.",
  },
  {
    name: "Bear Crawl (10m out and back)",
    emoji: "🐻",
    desc: "Low quadruped crawl. Core and shoulders pushed to the limit.",
  },
  {
    name: "Star Jumps",
    emoji: "⭐",
    desc: "Jump spreading arms and legs in the air. Total explosiveness.",
  },
  {
    name: "Devil's Press (dumbbells)",
    emoji: "😈",
    desc: "Burpee with row + dumbbell press. The most brutal exercise.",
  },
  {
    name: "Sprint in Place (burst)",
    emoji: "💨",
    desc: "Legs and arms at full speed for 40 seconds. No excuses.",
  },
  {
    name: "Lateral Shuffles",
    emoji: "↔️",
    desc: "Shuffle side to side with quick steps and low stance.",
  },
  {
    name: "Squat + Press (dumbbells)",
    emoji: "🏋️",
    desc: "Full squat + overhead press. Full body in one movement.",
  },
  {
    name: "Renegade Row (dumbbells)",
    emoji: "⚓",
    desc: "In plank position, alternate rows. Core + back + triceps.",
  },
  {
    name: "Kettlebell Swings",
    emoji: "🔔",
    desc: "Explosive hip hinge. High cadence for 40 seconds.",
  },
];

// ── Timer constants ─────────────────────────────────────────────────────────

export const WORK = 40;
export const REST = 20;

// ── Default selections ──────────────────────────────────────────────────────

export const getDefaultSel = (pool: { rec?: boolean }[]) =>
  pool
    .map((e: { rec?: boolean }, i: number) => (e.rec ? i : -1))
    .filter((i: number) => i !== -1);

export const DEFAULT_DAY_SEL = DAY_POOLS.map(getDefaultSel);
export const DEFAULT_HIIT_SEL = getDefaultSel(HIIT_POOL);
