import {
  Clock,
  Dumbbell,
  BookOpen,
  CalendarDays,
  Brain,
  Target,
  Flame,
  Coffee,
  Moon,
  Music,
  Droplets,
  Apple,
  Bike,
  HeartPulse,
  Pencil,
  Pill,
  Leaf,
  Laptop,
  Sunrise,
  Zap,
  Dog,
  Sparkles,
  Wind,
  Star,
  Banknote,
  UtensilsCrossed,
  Car,
  Gamepad2,
  Tv,
  Plane,
  ShoppingCart,
  GraduationCap,
  Home,
  Shirt,
  Smartphone,
  Gift,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

// ── Habit icon registry ───────────────────────────────────────────────────────
export const HABIT_ICON_MAP: Record<string, LucideIcon> = {
  clock:      Clock,
  dumbbell:   Dumbbell,
  bookOpen:   BookOpen,
  calendar:   CalendarDays,
  brain:      Brain,
  target:     Target,
  flame:      Flame,
  coffee:     Coffee,
  moon:       Moon,
  music:      Music,
  droplets:   Droplets,
  apple:      Apple,
  bike:       Bike,
  heartPulse: HeartPulse,
  pencil:     Pencil,
  pill:       Pill,
  leaf:       Leaf,
  laptop:     Laptop,
  sunrise:    Sunrise,
  zap:        Zap,
  dog:        Dog,
  sparkles:   Sparkles,
  wind:       Wind,
  star:       Star,
};

export const HABIT_ICON_KEYS = Object.keys(HABIT_ICON_MAP);

// ── Category icon registry ────────────────────────────────────────────────────
export const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
  banknote:   Banknote,
  laptop:     Laptop,
  utensils:   UtensilsCrossed,
  car:        Car,
  gamepad:    Gamepad2,
  tv:         Tv,
  heartPulse: HeartPulse,
  plane:      Plane,
  cart:       ShoppingCart,
  graduation: GraduationCap,
  pill:       Pill,
  dumbbell:   Dumbbell,
  coffee:     Coffee,
  dog:        Dog,
  music:      Music,
  home:       Home,
  shirt:      Shirt,
  zap:        Zap,
  smartphone: Smartphone,
  gift:       Gift,
};

export const CATEGORY_ICON_KEYS = Object.keys(CATEGORY_ICON_MAP);
